### ISSUE TITLE
[8.0] RETRY_INTERVAL error (unsupported type for timedelta seconds component: NoneType)

### ISSUE THREAD

**Issue by lefeverd** [OCA/connector#102]
Hello,
I encountered a bug when a RetryableJobError is raised.
The retry_postpone method is then called, without the keyword arg seconds.
This raises an error in job.py, method postpone:
TypeError: unsupported type for timedelta seconds component: NoneType

**Steps to reproduce**
- Create a job
- Raise a RetryableJobError

**Current Behaviour**
Traceback because of timedelta not allowing NoneType

**Expected Behaviour**
No traceback, job postponed.

**Comment by guewen** [comment]
Closed by #103
