### ISSUE TITLE
[8.0] retry_pattern bug in job decorator

### ISSUE THREAD

**Issue by lefeverd** [OCA/connector#104]
Hello,
as discussed in PR #103 I encountered a bug with the job decorator.
The retry_pattern does not work, as it is not returned in the functools.partial.

**Steps to reproduce**
- Create a task method that raises a raise RetryableJobError and annotate it with the job decorator, i.e.:

``` python
@job(retry_pattern={1: 5})
def dummy_task(session):
    raise RetryableJobError
```
- Run it with the connector

**Current Behaviour**
The job is postponed with the default RETRY_INTERVAL

**Expected Behaviour**
The job should be postponed with the interval specified in the retry_pattern.

**Comment by guewen** [comment]
Closed by #105
