### ISSUE TITLE
[8.0]AssertionError: 0 worker found in database instead of 1

### ISSUE THREAD

**Issue by flotho** [OCA/connector#109]
Hi,

I found that there was already an issue on the connector on #22 and its PR #24 
Yet I observe he same issue on the latest v8. Additionnaly, I don't find the same code in the file that has change. Any advice?

regards

**Comment by guewen** [comment]
Do you use the new Jobs Runner?

The fix #24 was removed because it was at most a workaround and the root cause was fixed (a race condition in the odoo's registry). So either the original root cause came back either we have another root cause, anyway maybe we should restore this workaround...
Still be warned that these workers will disappear in v9 in favor of the new jobs runner.

**Comment by guewen** [comment]
Looking in the code, the workaround with the return is still there https://github.com/OCA/connector/blob/8.0/connector/queue/model.py#L353. Meaning that it shows this message but does not fail,  the next times it tries to enqueue jobs, it should succeed, does it succeed to enqueue jobs later?

**Comment by flotho** [comment]
Hi @guewen 

a great thanks for your answer, actually I'm brand new on the specific technical aspects of the connector so I won't be able to say if I use the new jobs runner.
I pulled all the latest OCA repository.
The problem appears when I try to install the prestashop connector as I'm working on https://github.com/OCA/connector-prestashop/pull/11 
So it could come from that PR that is not respecting the new schema?

**Comment by guewen** [comment]
No it depends on the way you run Odoo. See this page for using the new job runner http://odoo-connector.com/guides/jobrunner.html

**Comment by flotho** [comment]
I've totally bypassed this part. I try this and let you know.
Anyway Thanks for your support,

**Comment by flotho** [comment]
Ok, in my logs I have some stuff like this :

```
2015-08-20 14:57:19,115 24022 INFO odoo-ysee openerp.service.server: Worker WorkerHTTP (24022) alive
2015-08-20 14:57:19,117 24023 INFO odoo-ysee openerp.service.server: Worker WorkerHTTP (24023) alive
2015-08-20 14:57:19,120 24024 INFO odoo-ysee openerp.service.server: Worker WorkerHTTP (24024) alive
```

So it seems to be launched.
Yet I'm not sure of those parts of the doc :

```
Do NOT start openerp-connector-worker.
```

How to be sure of that ? I use the odoo.py to start the server and add the load, is it enough?

```
Create jobs (eg using base_import_async) and observe they start immediately and in parallel.
```

Which kind of jobs are we talking about? Jobs from connector I imagine? I yes How can I test this?

**Comment by flotho** [comment]
@guewen,

A great thanks to you.
Also a great thanks to Roelt on #oca IRC who leads me to the good parameter, the environment option was a bash one an not a simple Odoo one. So I had to export the variable and not setting it in the odoo conf file.

Regards
