### ISSUE TITLE
Module Update and Groups

### ISSUE THREAD

**Issue by blaggacao** [OCA/connector#113]
It seams that on module update permission groups are not correctly updated, as beeing created dynamically (at installation). This breakes the User View. Is there any solution for this in OdooSA modules?

**Comment by guewen** [comment]
What permission groups do you mean?

**Comment by blaggacao** [comment]
there has been a dynamic in_group_xx which after an upgrade broke, the strange thing is, that in the actual version 3.1someting it uses sel_group_xx. Maybe we can vrify my line of thought by experience: Was there used in_group at some point in the past (version 2.x) ?

**Comment by guewen** [comment]
Connector never created any dynamic group. Could be something in another add-on?

**Comment by blaggacao** [comment]
I could not track it down better, closing this due to limited usefulness keeping it pending.
