### ISSUE TITLE
Is there a limit about the number of pending jobs?

### ISSUE THREAD

**Issue by sebalix** [OCA/connector#117]
I created 60k jobs (with chunks of 1000) in a first job, and at the same time the workers start to process them, all is fine.
But once the 60k jobs are created, and when I have about 33k remaining pending jobs, if I stop my server (properly, the current workers finish their tasks and terminate), and re-start it, the workers do not run anymore.
I thought it was due to some huge transactions to take some time, so I let the server like that the whole night, hoping the workers will recover and process these 33k pending jobs, but nothing happened.
To re-run the jobs, I just remove them directly in the db (`DELETE FROM queue_job WHERE job_function_id=X`), recreate the 60k jobs and this time all of them has been processed (without stopping Odoo).

I really don't know what's happening in fact, someone has experienced this?

Version used: 3.2

**Comment by guewen** [comment]
Do you run the legacy workers or the new jobs runner?

**Comment by sebalix** [comment]
@guewen I run the new jobs runner, with `ODOO_CONNECTOR_CHANNEL=root:4` (and 6 Odoo workers)

**Comment by guewen** [comment]
Fine. I observer similar effects in these situations:
- I had to force kill Odoo so some jobs were stuck in `started` and filled all the `root` channel seats
- I inadvertently started Odoo with the old workers before starting again with the runner which had an effect that I can't remember 

In any case, this can normally be solved simply by requeueing the `started` and `enqueued` jobs, either from the jobs view, either from the database (`UPDATE queue_job SET state = 'pending' WHERE state in ('enqueued', 'started')`)

**Comment by sebalix** [comment]
Got it! Thanks for the tip. The next time I will check the number of enqueued/started jobs.
So, before to restart a (production) environment, it could be advisable at first to set jobs as pending with your query, or to monitor them if they exceed the channel threshold.

**Comment by RoelAdriaans** [comment]
I have the same issues; 10 jobs, 4 channels and 4 jobs in state started.
After an Odoo restart there are no jobs started because 4 jobs are in state started but aren't really started..

I think the database should be cleaned up (with @guewen 's query) and there old jobs should be reset to state pending.

But when? Should we cleanup the database when we start Odoo, but that might fail if we have multiple odoo instances/machines with a single database. 
A cron might be a possibility, but i have jobs that range from 10 seconds to 8 hours or longer...

**Comment by guewen** [comment]
The documentation has been recently improved on this point: http://odoo-connector.com/guides/jobrunner.html#caveat 

You have to reset the jobs  with the query after the server is halted and before it is started. If you have several servers, **server** here means the one that runs the jobrunner.

Note that this situation is the result of a forced halt of the server so should not happen too frequently.  When stopping Odoo, you should ideally wait for the jobs to finish and Odoo will then stop by itself.

**Comment by sebalix** [comment]
@guewen I can't be 100% sure, but I think I encounter the problem without any server crash or "kill" signal, just by stoping/starting it normally. I will report here if it happens.

**Comment by guewen** [comment]
@sebalix if the revision of your odoo server is older than https://github.com/odoo/odoo/commit/d291aba4b5674b2bb2f29ea9425fd12b67419dc1 (PR https://github.com/odoo/odoo/pull/6738) you'll have the issue everytime you stop the server because Odoo itself was sending the wrong signal.

**Comment by sebalix** [comment]
@guewen I use OCB and update the branch regularly (on fba6da51e9d310589f70ba5df8462d2503be9dd3 currently). I hope to be wrong about the issue!
