### ISSUE TITLE
Redmine connector

### ISSUE THREAD

**Issue by thibault-monteiro** [OCA/connector#12]
Hi,

Do you have any example of redmine/openERP connector with your framework? 

Thanks

**Comment by guewen** [comment]
Hi,

I don't think there is an existing implementation for Redmine.

**Comment by thibault-monteiro** [comment]
Do you think it should be difficult to develop it?

**Comment by guewen** [comment]
I don't know Redmine nor your knowledge in Python / odoo so I can't give you a positive answer.

**Comment by bwrsandman** [comment]
@joaoalf has been working on such a connector
