### ISSUE TITLE
Snychronize metadata is working but jobs are in Pending State on Windows

### ISSUE THREAD

**Issue by JADCO5692** [OCA/connector#125]

**Comment by guewen** [comment]
Could you give more information about how you started Odoo and the job runner?
(does it run it multithreading or multiprocess, what is the Odoo version, do you start the job workers or the job runner and how...).

**Comment by guewen** [comment]
Did you read and applied http://odoo-connector.com/guides/jobrunner.html ?

**Comment by JADCO5692** [comment]
Yes.. But this is specific to Linux and not working in Windows.
Configuration is right as when i click on Synchronize metadata. The inital 6 records come up in Checkpoint Menu.

But when I click on Import Customer Group . A job is created and it remains in pending state and never get started

**Comment by guewen** [comment]
She Synchronize metadata button does not use the jobs.

Actually jobs have never been developed to work on Windows. We'll accept pull requests if you want to work to make it compatible with Windows. Still, I strongly advise you to run Odoo and connector on Linux.

**Comment by JADCO5692** [comment]
So, this cant work on windows.. :(

**Comment by guewen** [comment]
It might work but nobody AFAIK has ensured about that.

**Comment by JADCO5692** [comment]
Ya... I am struggling with that... I have tried all the listed solutions available but none of them worked.

Thought that it would on Windows too.. but :(
