### ISSUE TITLE
Sale import Error - Odoo 8 - Magento 1.9.2

### ISSUE THREAD

**Issue by risamnang** [OCA/connector#133]
Hello,

I need to import sales and get this error : 

Fault 1: "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'imported' in 'where clause', query was: SELECT `main_table`.`increment_id` FROM `sales_flat_order` AS `main_table` WHERE (imported = '') AND (created_at >= '2015/10/26 09:51:39' AND created_at <= '2015/10/26 14:25:31') AND (store_id IN('1')) AND (state != 'canceled')">

Is anyone could please give me the solution ?

**Comment by guewen** [comment]
Could you report your issue on the proper project http://github.com/oca/connector-magento/issues please?
