### ISSUE TITLE
[8.0]Jobs seems to be freezed

### ISSUE THREAD

**Issue by flotho** [OCA/connector#141]
Hi everyone,

I'm working with the prestashop connector and I have some strange phenomenon. From time to time, some jobs are stucked in the queue an block everything (server is not restarted, I already aware of jobrunner caveat). It looks like some long duration jobs are locking the channel. 
I try to adapt the cron so that the jobs are not using the ressource simultaneously.
Any chance to have a tip for  preventing this?

regards

**Comment by guewen** [comment]
Do you use the HEAD of the 8.0 branch? A few fixes have been made recently for uses cases where Retryable errors stick the job in `started`.

If you are using already using the latest revision, I would also investigate if a timeout is defined for the stock communicating with Prestashop. Possibly it could be waiting for a response.

**Comment by flotho** [comment]
Thanks @guewen I'll try those improvements and let you know.
Additionnaly I was a kind of recursive call of the same jobs in my connector.
So thanks to my fix and the awesome improvements of connector, it should be working now ;-)
