### ISSUE TITLE
Job stuck in 'enqueued'

### ISSUE THREAD

**Issue by guewen** [OCA/connector#148]
We had this case today with the jobrunner (version 7.0).

A job was stuck in `enqueued`, blocking the queue because it took a place, considered as a running job.

Our analysis was that the jobrunner updated the state of the job to enqueued, but the `GET` call to run the job on the Odoo workers had never reached Odoo (no trace of `GET` for this job in the logs). The reason why the `GET` call was not done is unknown (other jobs were correctly processed just before).

In the runner's logs, we have:

```

2015-11-17 18:25:27,873 9168 INFO ? openerp.addons.connector.jobrunner.runner: asking Odoo to run job a9e5d41a-433f-43e5-b584-e6991cf2a64e on db openerp_prod_xxx
2015-11-17 18:25:27,876 9168 INFO ? requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): localhost
```

So we expect to have this in the Odoo logs:

```
2015-11-17 18:25:27,876 5327 INFO openerp_prod_xxx werkzeug: 127.0.0.1 - - [17/Nov/2015 18:25:27] "GET /connector/runjob?db=openerp_prod_xxx&job_uuid=a9e5d41a-433f-43e5-b584-e6991cf2a64e HTTP/1.1" 200 -
```

But there is nothing.

In a general manner, if anything goes wrong when we call `_async_http_get` (https://github.com/OCA/connector/blob/9.0/connector/jobrunner/runner.py#L134-L149) (which is very rare but could happen), a job will stay stuck in `enqueued` state.

A possible workaround would be to add a cron that check if a job is enqueued for too long and requeue it. But I wonder if we couldn't find a nicer way to fix it (what about removing the `enqueued` state? side-effects?)

@sbidoul @lmignon  you surely have ideas :-)

**Comment by lmignon** [comment]
@guewen In the `_async_http_get` exception are ignored . Am I wrong if I say that if an exception occur, the job will stay in the  'enqueued' state and block the queue?   IMO in the `_async_http_get` method we should set the job state to 'failed' if an error occurs and the state is 'enqueued'.

**Comment by guewen** [comment]
> @guewen In the _async_http_get exception are ignored . Am I wrong if I say that if an exception occur, the job will stay in the 'enqueued' state and block the queue? IMO in the _async_http_get method we should set the job state to 'failed' if an error occurs and the state is 'enqueued'.

That is exactly that. Neat idea, still I think we should set it back to `pending` as the error does not come  from the job but from the communication between the jobrunner and odoo.

**Comment by lmignon** [comment]
@guewen for the record, @laetitia-gangloff says me that we encountered one week ago the same problem for one of our client in 7.0

> still I think we should set it back to `pending`

You're right the state should be set back to `pending`.

**Comment by sbidoul** [comment]
I guess this one be closed?
