### ISSUE TITLE
connector module not found

### ISSUE THREAD

**Issue by riess82** [OCA/connector#160]
Using the installation instructions I cloned the git repos. All modules showed up correctly, except the "connector" itself. I worked around the issue for now by copying connector/connector to connector and deleting the line "application: True". That is ok for me in a testing environment, but not good for production. This is using v7.

**Comment by guewen** [comment]
Could you show how you cloned the repository (its path and the result of `ls`) and what do you have in the addons-path?
I don't see what the `application: True` might change anything except that it is displayed differently accordingly to the search filter you use in the `Local Modules` menu.

**Comment by riess82** [comment]
about application: True, yes maybe that has nothing to do with it...
I used git clone git@github.com:OCA/connector.git -b 7.0 to get the repo (from install guide).
ls inside the created directory "connector" gives connector  connector_base_product  LICENSE  README.md
and the module connector_base_product shows up under modules which gave me the idea to try removing the "application"

**Comment by guewen** [comment]
Can you do `pwd` inside your git clone and can you show your addons-path?

**Comment by riess82** [comment]
pwd Outputs: /opt/openerp/extra-special-addons/connector
addons path from openerp.conf:
addons_path = /opt/openerp/server/openerp/addons,/opt/openerp/special-addons,/opt/openerp/extra-special-addons,/opt/openerp/extra-special-addons/connector,/opt/openerp/extra-special-addons/connector-magento,/opt/openerp/extra-special-addons/connector-ecommerce,/opt/openerp/extra-special-addons/sale-workflow,/opt/openerp/extra-special-addons/e-commerce,/opt/openerp/extra-special-addons/product-attribute

**Comment by guewen** [comment]
Weird... no special warning in the logs?
Could it be a access rights error?
What if you run `find /opt/openerp -type d -name connector`?

**Comment by riess82** [comment]
Nothing in the logs. Access rights are out of the question as 1) the module next to it is found. 2) when copying the files to a different Location it works.
 find /opt/openerp -type d -name connector Outputs:
find: "/opt/openerp/extra-special-addons/openerp-display_test_env/static": Keine Berechtigung
/opt/openerp/extra-special-addons/connector
the first line is something completely different, the Location found now is the one i copied the files to to get it working.
Could it be related to some Problem inside the dependencies when the location of the modules is Directory "connector" and the module has the same Name "connector"?

**Comment by guewen** [comment]
Say if I'm wrong, but the find should return at least:

```
/opt/openerp/extra-special-addons/connector
/opt/openerp/extra-special-addons/connector/connector
```

> Could it be related to some Problem inside the dependencies when the location of the modules is Directory "connector" and the module has the same Name "connector"?

This is the setup I use everywhere without any issue.

**Comment by guewen** [comment]
> Could it be related to some Problem inside the dependencies when the location of the modules is Directory "connector" and the module has the same Name "connector"?

I got it. You put `/opt/openerp/extra-special-addons` in your addons-path, you shouldn't do that. By doing this indeed you shadow the `connector` module with the `connector` repository.

**Comment by riess82** [comment]
thank you for that info and solving the puzzle. I have my own custom modules in that Directory and used the git commands in there which i thought was a tidy Thing to do.  But it is no Problem at all to move move my modules down to the same directory Level as the connector and Change their path.

**Comment by guewen** [comment]
> But it is no Problem at all to move move my modules down to the same directory Level as the connector and Change their path.

This is the cleanest way to do it.
