### ISSUE TITLE
Unit test using worker from connector

### ISSUE THREAD

**Issue by kaerdsar** [OCA/connector#168]
Hi, 

I'm creating some unit test for testing some mails invitations, that uses the connector module. In my current code when a user sends an invitation, then a job is created and later the worker runs the job sending the email.

My problem is that I need the test also works with the worker from connector. In the unit test I can create a worker and also the worker finds the new job but it can't run it. I guess the problem is with sessions, maybe in test environment something is locked and new sessions doesn't work.

I noticed that the watcher started but it can't finish the: self._update_workers(). I also checked in the unit test from connector module, but the worker tests are not done.

It would help a lot some ideas about **how to do unit tests that using the worker**.

**Comment by guewen** [comment]
The issue with jobs are their asynchronous execution where for a test you really need a synchronous execution. You shouldn't try to use the worker only to be able to test your code. My advice is to use [mock_job_delay_to_direct](https://github.com/OCA/connector/blob/8.0/connector/tests/common.py#L29) which will replace the `delay()` by a direct synchronous execution. You can find an example here: https://github.com/OCA/connector-magento/blob/8.0/magentoerpconnect/tests/test_export_picking.py#L71

**Comment by kaerdsar** [comment]
Thanks for the advice. I will try ...

**Comment by kaerdsar** [comment]
I successfully did the test. I had to adapt the mock_job_delay_to_direct method to my environment and it worked. Nice approach to create unit test for jobs. Thank you very much @guewen .
