### ISSUE TITLE
Documentation on odoo-connector.com for every version

### ISSUE THREAD

**Issue by guewen** [OCA/connector#176]
Currently, the only documentation pushed on odoo-connector.com is the 8.0 version (https://github.com/OCA/connector/blob/9.0/.travis_push_doc#L5).

We should push all versions in sub-directories (7.0, 8.0, 9.0) with an index that redirects on the last version and have a link for the different versions (like we do for the languages).

**Comment by lasley** [comment]
@guewen - were you looking to do more here than https://github.com/OCA/connector/commit/b743523f5ca31d4a02a69a3f603bcd6c86a1147c?

**Comment by guewen** [comment]
@lasley Nope, I just didn't thought I had created an issue for that. Thanks for the tracking :)
