### ISSUE TITLE
[question] Google Contacts Sync

### ISSUE THREAD

**Issue by ivantodorovich** [OCA/connector#181]
Do you know of the existance of any module sync'ing partners to a Google Contacts?
We don't really need a two way sync, one way Odoo -> Google would work just fine.

We'll probably develop this, but since it's something rather common it shocks us not having found anything like this on the web. 

Maybe someone found anything we didn't?

**Comment by jshah4015** [comment]
I am also unable to find such a module. I was similarly shocked by not having such module with usual practices

**Comment by guewen** [comment]
Not aware of such thing
