### ISSUE TITLE
Jobs remains pending state

### ISSUE THREAD

**Issue by deepika-bhojani-flectra** [OCA/connector#182]
The jobs created after importing anything remains in pending state. It is not En queued or Started. 
As workers have been removed from connector the scheduler is no more available, so jobs are not executed.
Anyone have idea regarding this issue?

**Comment by guewen** [comment]
Workers have been replaced by the job runner, please refer to this documentation: http://odoo-connector.com/guides/jobrunner.html

**Comment by deepika-bhojani-flectra** [comment]
how to use job runners?
i used --workers=5 and --log-handler=openerp.addons.connector:DEBUG in my path.
still jobs remain in pending state.

**Comment by sbidoul** [comment]
@DeepikaBhojani it is explained in details here: http://odoo-connector.com/guides/jobrunner.html#how-to-use-it

Please follow these steps very carefully.

**Comment by deepika-bhojani-flectra** [comment]
i followed the steps and I am getting this traceback:

Traceback (most recent call last):
  File "/home/erp/workspace/git/wordpress/connector/connector/jobrunner/runner.py", line 331, in run
    self.initialize_databases()
  File "/home/erp/workspace/git/wordpress/connector/connector/jobrunner/runner.py", line 273, in initialize_databases
    db = Database(db_name)
  File "/home/erp/workspace/git/wordpress/connector/connector/jobrunner/runner.py", line 159, in **init**
    connection_info = openerp.sql_db.connection_info_for(db_name)[1]
AttributeError: 'module' object has no attribute 'connection_info_for'

i cant find connection_info_for method anywhere.

**Comment by sbidoul** [comment]
@DeepikaBhojani it seems you are trying to run the 9.0 version of connector on Odoo 8.0.

**Comment by deepika-bhojani-flectra** [comment]
I am running 9.0 version of connector in Odoo 9.0.

**Comment by sbidoul** [comment]
It's there on the 9.0 branch: https://github.com/odoo/odoo/blob/9.0/openerp/sql_db.py#L650

It's been added on Nov 23, 2015, so maybe you have a very old version of Odoo 9.0?
