### ISSUE TITLE
jobs triggered double because of sync issue when running 2 odoo instances

### ISSUE THREAD

**Issue by Benniphx** [OCA/connector#190]
I have a strange issue:

In one of our projects we use the connector to send emails. 
Everything works exact as expected.
But on the live system sometimes emails / jobs are triggered twice.
Not 2 jobs are created the job is just executed twice.

The setup is 2 odoo instances on 2 server with one combined database.

I tried to reproduce the error local and also run 2 instanced of odoo with one database. I realized that one of the odoo's tried to execute the job a second time but odoo saw that the other instance already executed the job because of the immediately local sync between the 2 odoo instances.

You will see in the log:

```
2016-04-19 08:01:13,166 8204 WARNING 2587 openerp.addons.connector.controllers.main: job a5cc7167-1103-4f26-bb63-d29b8b88fe0e is in state done instead of enqueued in /runjob
2016-04-19 08:01:13,166 8204 WARNING 2587 openerp.http: <function openerp.addons.connector.controllers.main.runjob> returns an invalid response type for an http request
```

Because the 2 odoo's on live are not sync like local we have the problem that jobs sometimes are executed double. 

Any idea how to add or enable a check with a small delay to see if the job is really already executed ?

**Comment by guewen** [comment]
The jobrunner should run on only one of the instance.

**Comment by Benniphx** [comment]
@guewen Thank you for the quick reply! I will try this.

**Comment by christophlsa** [comment]
@guewen 
For the first it's ok. Short question: Is it sufficient to omit the ODOO_CONNECTOR_CHANNELS and the `load` config parameter at the second instance?

Besides this a general question: We have two servers with one odoo server per server to reach redundancy. But if we deactivate the jobrunner on one instance and later the instance with the jobrunner goes down (server/network issues) then no jobrunner is running anymore. Do you think we can improve the jobrunner to better block jobs by a jobrunner to support more than on jobrunner?

**Comment by sbidoul** [comment]
> Is it sufficient to omit the ODOO_CONNECTOR_CHANNELS and the load config parameter at the second instance?

In Odoo 8.0 it is sufficient. In Odoo 9.0 the job runner starts unconditionally.

> Do you think we can improve the jobrunner to better block jobs by a jobrunner to support more than on jobrunner?

Yes, there is a TODO for that in the code:
https://github.com/OCA/connector/blob/017b57c50fb486c6ff51c32863c4cdaf47193bf6/connector/controllers/main.py#L58

I did not think it was important so far, but your use case seems legitimate to me.

**Comment by sbidoul** [comment]
@christophlsa omitting `--load=connector` may prevent the connector to start in 9.0 too. To be tested.
