### ISSUE TITLE
[7.0] job runners and relative imports

### ISSUE THREAD

**Issue by florian-dacosta** [OCA/connector#192]
Hello,

I am trying to make the jobrunner work for an odoo version 7.
But when I run the openerp-connector-runner script, I get this error : 

  File "/usr/local/lib/python2.7/dist-packages/requests/**init**.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/**init**.py", line 3, in <module>
    from . import urllib3
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/**init**.py", line 10, in <module>
    from .connectionpool import (
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 10, in <module>
    from queue import LifoQueue, Empty, Full
  File "/home/florian/dev/openerp7/connector/connector/queue/**init**.py", line 22, in <module>
    from . import model
  File "/home/florian/dev/openerp7/connector/connector/queue/model.py", line 33, in <module>
    from .job import STATES, DONE, PENDING, OpenERPJobStorage, JOB_REGISTRY
  File "/home/florian/dev/openerp7/connector/connector/queue/job.py", line 35, in <module>
    from ..exception import (NotReadableJobError,
ValueError: Attempted relative import beyond toplevel package

If I change the way to import in these files I get rid of the error : 
- connector/queue/job.py
- connector/queue/model.py
- connector/queue/worker.py

(Replacing : `from ..exception import (NotReadableJobError)` by `from openerp.addons.connector.exception import (NotReadableJobError)`)
But I wonder if I do something wrong, because I doubt nobody is using the job runner with a version 7.0

The only things I do is : 
export ODOO_CONNECTOR_CHANNELS=root:4
python ../connector/connector/openerp-connector-runner -d db_name -c conf_file

Am I missing something?
Thanks for the feedback

**Comment by guewen** [comment]
Did you set the [`PYTHONPATH` to the path of the Odoo server](https://github.com/OCA/connector/blob/7.0/connector/openerp-connector-runner#L26-L28)?

Example: `ODOO_CONNECTOR_CHANNELS=root:4 PYTHONPATH=/path/to/odoo/server/ python ../connector/connector/openerp-connector-runner -d db_name -c conf_file`

**Comment by florian-dacosta** [comment]
yes, I forgot to put this step but I did it.
else I have the error : 
  File "../connector/connector/openerp-connector-runner", line 33, in <module>
    import openerp
ImportError: No module named openerp

**Comment by guewen** [comment]
> File "../connector/connector/openerp-connector-runner", line 33, in
> import openerp

Looks like the path to your server is not correct if it can't import openerp?

**Comment by florian-dacosta** [comment]
No, I mean, before setting the path, it can't import openerp.
After setting the path, the error is 
from ..exception import (NotReadableJobError,
ValueError: Attempted relative import beyond toplevel package

So it can find openerp

**Comment by florian-dacosta** [comment]
Sorry, I was not not very clear, so, let's resume, 
What I did : 
export ODOO_CONNECTOR_CHANNELS=root:4
export PYTHONPATH=path/to/odoo
python ../connector/connector/openerp-connector-runner -d db_name -c conf_file

Then I had the error :
from ..exception import (NotReadableJobError,
ValueError: Attempted relative import beyond toplevel package

Then I have replaced `from ..exception import (NotReadableJobError)` by `from openerp.addons.connector.exception import (NotReadableJobError)`) in connector/queue/job.py files and 2 others.

Now, job runner is working fine.

The thing is I do not want to diverge from the connector OCA branch...

**Comment by guewen** [comment]
I use it through an anybox buildout command so I'm of limited support... :-(

@lmignon do you run in the same way than @florian-dacosta ?

**Comment by florian-dacosta** [comment]
Yes, I think I would not have the problem throught buildout.
Would it be fine to make a PR to change the way to import in these files?
connector/queue/job.py
connector/queue/model.py
connector/queue/worker.py
I do not think it could lead to any regression.

**Comment by guewen** [comment]
I would prefer if we find the root cause. Relative import is correct here and maybe that's in `openerp-connector-runner` or the way we run it that we have to fix something.

**Comment by sebastienbeau** [comment]
Moving the executable openerp-connector-runner  outside of the branch solve the issue see here : https://lists.launchpad.net/openerp-connector-community/msg00614.html
