### ISSUE TITLE
EDI Connector

### ISSUE THREAD

**Issue by lasley** [OCA/connector#195]
I am looking for an EDI interface for Odoo 9, which was dropped from official support. As such, I am thinking of using the connector to create a platform to allow this. 

I found this https://odoo-community.org/groups/connectors-30/connectors-29124?mode=thread where @jbeficent mentioned that this is something the OCA community might want, and that we may want to consider using Bots as the translator. Looks like there's a solid Python module for this, so we seem good to go there.

Before I start I would like to make sure that I am not overlapping pre-existing pieces of OCA functionality that I am too new to know about, and confirm if someone else has already begun this. If anyone has any suggestions (including where this module should actually go), they are welcome as well 😄

**Comment by CGenie** [comment]
Hi, I plan to do EDI connection in some near future so we can join forces :)

**Comment by guewen** [comment]
That would be in https://github.com/OCA/connector-interfaces I think
