### ISSUE TITLE
Performance of queue_job lookups 

### ISSUE THREAD

**Issue by gracinet** [OCA/connector#196]
The queue system does frequent lookups in the queue_job table, checking for jobs to process. 
I have an installation on hand where the queue_job table has grown so big that this becomes a bottleneck (200ms time for a SELECT, that can easily be spared)

I get much better results (sub-ms range) after these two actions:
- CREATE INDEX queue_job_state_active_idx ON queue_job(active, state);
- stop using the NOT IN in this request, so that PostgreSQL can use the index

```
        sql = ("SELECT id FROM queue_job "
               "WHERE worker_id IS NULL "
               "AND state not in ('failed', 'done') "
               "AND active = true "
               "ORDER BY eta NULLS LAST, priority, date_created ")
```

That installtion is on an old version for OpenERP 7.0, but I've already compared with current 7.0 and 8.0 branches of the selector, it seems to be the same.

I'm not sure what the OCA policy says about creating indexes, but I'm naturally more than willing to submit my fixes

**Comment by gracinet** [comment]
FIxed CREATE INDEX in description

**Comment by guewen** [comment]
I see no problem with adding an index in general.
For this particular case, this code is used by the workers which are deprecated (removed in 9.0), so I would recommend to start using the Jobrunner.

**Comment by sbidoul** [comment]
Hi @gracinet,

The index you propose makes sense to me.

Which, by the way, makes me realize that this active flag is completely ignored by the new jobrunner. Nobody ever complained about that, though. So I'm wondering maybe this active check could be abandoned and relying on `select=True` on the state field would be enough as an index?

Finally, the new jobrunner does `in NOT_DONE` so that part should not be an issue with the jobrunner, and the NOT_DONE constant can be used in the worker query: https://github.com/OCA/connector/blob/2e20944e86b9ac70505d02607e650bc3750aa421/connector/jobrunner/runner.py#L292

Is there any chance you can switch to the jobrunner on that installation?

**Comment by gracinet** [comment]
@guewen @sbidoul thank you both for so quick a reply.
It's been some time, and I very rarely code in Odoo realm these days, so I didn't know about this new jobrunner. Thanks you for pointing it out to me.

The `in NOT_DONE` that you describe, @sbidoul is about the same solution I've came up with in the workers context. I'll investigate if switching to the jobrunner in that 7.0 installation is doable for medium term support. For the short term, I'm already happy with a dedicated branch, but I'd like to stick back to upstream one way or the other.

**Comment by guewen** [comment]
> Which, by the way, makes me realize that this active flag is completely ignored by the new jobrunner. Nobody ever complained about that, though. So I'm wondering maybe this active check could be abandoned and relying on select=True on the state field would be enough as an index?

I'd want to deprecate this `active` field which was introduced for special cases but which revealed a very bad idea IMO. The idea was that an exception `NothingToDoJob` raised during the execution of a job was changing `active` to `False` so we could hide some sort of useless jobs. Now, this is really confusing and there is not a single case where I'd want to use this feature.

**Comment by sbidoul** [comment]
@guewen :+1: we can drop the active flag in 9.0 since it's ignored by the runner anyway.
