### ISSUE TITLE
[9.0] Installing connector blocks access to General Settings

### ISSUE THREAD

**Issue by aisopuro** [OCA/connector#199]
1. Start at the main dashboard.
2. Go to Settings
3. Click the "General settings" menu item at the top of the page.
#### Expected behaviour

The General settings view is opened
#### Actual behaviour

The General settings button opens a dropdown, which reveals a signle "Connector" option. Odoo no longer treats the button as a link, which means we can no longer get into the general settings.

![image](https://cloud.githubusercontent.com/assets/2587901/15938035/06852a00-2e7a-11e6-864a-da65b938ffa4.png)

My suspicion is that this is because of some change in the way Odoo 9 treats menu definitions. If the connector needs its own settings, it could maybe be put under its own menu, or moved under Technical.

**Comment by lasley** [comment]
Hi @aisopuro - Thanks for the report. Are you using the most up to date version? I moved it to technical settings in #191

**Comment by aisopuro** [comment]
Ah, of course. Yeah, I'm using an older version. I'll update when the project allows and re-open this if there's still a problem, but it seems like @lasley was way ahead of me here. :+1:
