### ISSUE TITLE
Deprecation Warning openerp.pooler.get_db_and_pool() is deprecated. in v8.0

### ISSUE THREAD

**Issue by nbessi** [OCA/connector#20]
It floods the log files

**Comment by yucer** [comment]
Just for info: What should be used in cases like this: http://bit.ly/1USZQZM

I mean in post-upgrade scripts ?

**Comment by yucer** [comment]
Sorry It was a dummy question. registry() should be used then, as the commit explains.

I suppose that openupgrade use it to be compatible with old versions while updating them.
