### ISSUE TITLE
Why the job runner is not working?

### ISSUE THREAD

**Issue by harunyasar** [OCA/connector#202]
I followed and performed instructions in this [link](http://odoo-connector.com/guides/jobrunner.html). When I start the Odoo application I couldn't see the debug messages. I guess job runner is not starting.

I'm running my Odoo app in Odoo 9 Docker container. For more information:
https://hub.docker.com/_/odoo/

**Comment by sbidoul** [comment]
Please provide more information:
- command line used to start odoo with all options, including `--log-handler=openerp.addons.connector:DEBUG`
- log file

**Comment by harunyasar** [comment]
Here is my openerp-server.conf:
`workers = 4`
`server_wide_modules=web,web_kanban,connector`
`log_handler = :INFO,openerp.addons.connector:DEBUG`
`max_cron_threads = 5`
and is Docker file config lines:
`ENV ODOO_CONNECTOR_CHANNELS root:2,root.channel:2`
`ENV ODOO_CONNECTOR_PORT 8069`

Current logs:

> odoo_1     | 2016-08-11 14:45:34,920 1 INFO ? openerp.service.server: AutoReload watcher running
> odoo_1     | 2016-08-11 14:45:34,978 16 INFO ? openerp.service.server: Worker WorkerHTTP (16) alive
> odoo_1     | 2016-08-11 14:45:34,993 17 INFO ? openerp.service.server: Worker WorkerHTTP (17) alive
> odoo_1     | 2016-08-11 14:45:35,110 18 INFO ? openerp.service.server: Worker WorkerHTTP (18) alive
> odoo_1     | 2016-08-11 14:45:35,117 19 INFO ? openerp.service.server: Worker WorkerHTTP (19) alive
> odoo_1     | 2016-08-11 14:45:35,192 21 INFO ? openerp.service.server: Worker WorkerCron (21) alive
> odoo_1     | 2016-08-11 14:45:35,227 22 INFO ? openerp.service.server: Worker WorkerCron (22) alive
> odoo_1     | 2016-08-11 14:45:35,307 25 INFO ? openerp.service.server: Worker WorkerCron (25) alive
> odoo_1     | 2016-08-11 14:45:35,328 24 INFO ? openerp.service.server: Worker WorkerCron (24) alive
> odoo_1     | 2016-08-11 14:45:35,286 23 INFO ? openerp.service.server: Worker WorkerCron (23) alive
> odoo_1     | 2016-08-11 14:45:37,186 20 INFO ? openerp: OpenERP version 9.0c-20160726
> odoo_1     | 2016-08-11 14:45:37,186 20 INFO ? openerp: addons paths: ['/var/lib/odoo/addons/9.0', u'/usr/lib/python2.7/dist-packages/openerp/addons', u'/mnt/extra-addons']
> odoo_1     | 2016-08-11 14:45:37,187 20 INFO ? openerp: database: odoo@172.17.0.2:5432
> odoo_1     | 2016-08-11 14:45:37,757 20 INFO ? openerp.service.server: Watching addons folder /var/lib/odoo/addons/9.0
> odoo_1     | 2016-08-11 14:45:37,757 20 INFO ? openerp.service.server: Watching addons folder /usr/lib/python2.7/dist-packages/openerp/addons
> odoo_1     | 2016-08-11 14:45:37,760 20 INFO ? openerp.service.server: Watching addons folder /mnt/extra-addons
> odoo_1     | 2016-08-11 14:45:42,895 18 INFO ? openerp.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
> odoo_1     | 2016-08-11 14:45:44,090 18 INFO ? openerp.http: HTTP Configuring static files
> odoo_1     | 2016-08-11 14:45:44,188 18 INFO opusv9 openerp.modules.loading: loading 1 modules...
> odoo_1     | 2016-08-11 14:45:44,203 18 INFO opusv9 openerp.modules.loading: 1 modules loaded in 0.01s, 0 queries
> odoo_1     | 2016-08-11 14:45:44,250 18 INFO opusv9 openerp.modules.loading: loading 24 modules...
> odoo_1     | 2016-08-11 14:45:44,543 18 INFO opusv9 openerp.modules.loading: 24 modules loaded in 0.29s, 0 queries
> odoo_1     | 2016-08-11 14:45:44,926 18 INFO opusv9 openerp.modules.loading: Modules loaded.
> odoo_1     | 2016-08-11 14:45:44,929 18 INFO opusv9 openerp.addons.base.ir.ir_http: Generating routing map
> odoo_1     | 2016-08-11 14:45:45,131 18 ERROR opusv9 openerp.http: Exception during JSON request handling.

Thats all.

@sbidoul do you have any idea?

**Comment by guewen** [comment]
@harunyasar do you run the odoo CLI with the `--load=web,web_kanban,connector` option?

**Comment by harunyasar** [comment]
@guewen this option is same, isn't it?
`server_wide_modules=web,web_kanban,connector`

**Comment by guewen** [comment]
@harunyasar My reading of the odoo's code indicates me that `server_wide_modules` is not read from the configuration file, but I might be wrong. Did you try with the `--load` option?

**Comment by sebalix** [comment]
I encountered the same problem, I'm unable to load modules with the `server_wide_modules` option in the configuration file, it only works when passing the `--load` option on the command line (so your init scripts should take care of that). IMO it is a Odoo bug.

**Comment by harunyasar** [comment]
@guewen i think it might be please check this line.

https://github.com/odoo/odoo/blob/9.0/openerp/tools/config.py#L114

i couldn't try because the app is running with docker container.

@sebalix omg! i didn't know it.

i'll create a new odoo image via different base image and try to `--load` option.

**Comment by guewen** [comment]
@harunyasar the line you show is the CLI option. The keys read from the config file are 
https://github.com/odoo/odoo/blob/9.0/openerp/tools/config.py#L384-L399

@sebalix thanks for confirming

**Comment by harunyasar** [comment]
@guewen is this mean just declarations in `keys` variable will execute? ok i got it. next i'll try `--load` option.

**Comment by lasley** [comment]
@harunyasar - did `--load` resolve this issue?

**Comment by harunyasar** [comment]
@lasley i could not try because i'm on vacation. when i turn back home absolutely i'll try and add feedback.

**Comment by harunyasar** [comment]
@lasley and all apologise for lateness. `--load` parameter solved my problem. thanks for anyone who helps me.

**Comment by nilshamerlinck** [comment]
For the record, this was fixed at Odoo level by https://github.com/odoo/odoo/commit/5ee4344efd0074fac4006984c1eb1ccc4f335518
