### ISSUE TITLE
Blueprint: per channel delay between jobs

### ISSUE THREAD

**Issue by sbidoul** [OCA/connector#203]
# Goal

The current channel configuration mechanism allows to limit the number of jobs that can run in parallel. However, as soon as there is available capacity, the next job runs immediately (provided there is capacity in the downstream channel, of course). 

Some third party systems have rate limitation systems that reject requests that arrive with a too high frequency. 

To cope with such systems, I propose to extend the channel configuration mechanism to implement a delay betwen the dequeing of successive jobs.
# Configuration

The channel configuration string will accept a new key 'delay' whose value is the delay between jobs in seconds.

https://github.com/OCA/connector/blob/0df11a02610c04cd600ce087ff9ba274113c403d/connector/jobrunner/channels.py#L539
# Implementation

It should be as simple as using this delay option to compute the time before which no job can be dequed in the channel, then breaking the get_jobs_to_run loop if that time is not reached.

https://github.com/OCA/connector/blob/0df11a02610c04cd600ce087ff9ba274113c403d/connector/jobrunner/channels.py#L460

**Comment by sbidoul** [comment]
@lmignon @guewen

**Comment by guewen** [comment]
I really like the idea! your proposal LGTM

**Comment by lasley** [comment]
I like as well; this is going to be incredibly useful with externally hosted APIs

**Comment by lmignon** [comment]
:+1: The proposal looks good to me too.

**Comment by sbidoul** [comment]
Here you go: #205
