### ISSUE TITLE
Backend Test deletes backends on other modules

### ISSUE THREAD

**Issue by ghost** [OCA/connector#222]
Test on backends removes any backend that is already registered, so they are not accessible through the test environment.

https://github.com/OCA/connector/blob/9.0/connector/tests/test_backend.py#L26

**Comment by guewen** [comment]
Could you give more details on what you are doing and what did you expected?

**Comment by ghost** [comment]
We have created backend tests on a module with a dependency to connector (obviously), and when our tests are loaded, the connector test removes all the backends in the system (as it is a global variable it is shared between all the modules).
