### ISSUE TITLE
Odoo to Odoo connector, is this a good framework to start with?

### ISSUE THREAD

**Issue by BzMB** [OCA/connector#233]
Hello OCA!

Thanks for all your work on the connector!

In a scenario of connecting one Odoo (odoo10community) to another Odoo (odoo10community), do you think that this framework represents a good start?

Connector Aim:
Passing a confirm sale order (system1) as a purchase order onto the (system2).

We known that there is the multi company feature but we want to keep separate the 2 systems/databases.

Any other feedback on that will be much appreciate.

Thank you!
Bizitas

**Comment by pedrobaeza** [comment]
See https://github.com/OCA/connector-odoo2odoo project
