### ISSUE TITLE
dependencies queue_job

### ISSUE THREAD

**Issue by Hamza-Talibi** [OCA/connector#237]
Hello,
I'm trying to install the last version of connector, and  I get error in dependencies because the module queue_job doesn't exist.
I looked for it, but I don't find it.
Can you help me?
Thank you.
Best regards

**Comment by simahawk** [comment]
Hi,

that module has been moved to https://github.com/OCA/queue/.

Cheers,
S.

**Comment by Hamza-Talibi** [comment]
Thank you so much.
