### ISSUE TITLE
Unknown channel problem

### ISSUE THREAD

**Issue by harunyasar** [OCA/connector#241]
Hello there!

Although my custom connector application has already a subchannel that work under the root, Connector has been sending me a warning like;

`unknown channel root.subchannel, using root channel for job bdd353fc-d9ce-4273-a161-67c499288cfe`

I guess when the application is running my sub channel haven't been set correctly.

Thanks.

**Comment by harunyasar** [comment]
I solved the problem by setting environment variable like this:

```
ODOO_CONNECTOR_CHANNELS=root:2,root.sub:2
ODOO_CONNECTOR_PORT=8069
```

Then another question spring up here: what is the correct format that setting the option in Odoo config file.

```
channels = root:2, root.sub:2
channels = root:2 root.sub:2
```

Which one is correct?

**Comment by pedrobaeza** [comment]
See documentation: http://odoo-connector.com/guides/jobrunner.html#how-to-configure-channels
