### ISSUE TITLE
Integrating Odoo presta connector

### ISSUE THREAD

**Issue by Razgort** [OCA/connector#246]
Hi,
I've opened an issue on connector prestashop but have been redirected here so here is my problem and the tons of errors i get =(

I'm integrated Odoo connector prestashop in my Odoo 9 OCB version.
The connector is installed. But when i want to make a sale on odoo, i get a lot of errors like these bellow

I installed the connector based on the configuration of guewen : https://github.com/guewen/odoo-prestashop-dev

![screen shot 05-17-17 at 08 22 am](https://cloud.githubusercontent.com/assets/9212658/26141110/88d866a8-3ada-11e7-9e74-4fd513e155a1.PNG)

this error comes repeatedly when i start my odoo with the connector.

![screen shot 05-16-17 at 05 07 pm](https://cloud.githubusercontent.com/assets/9212658/26141116/926b5784-3ada-11e7-9605-a4afe0d7e2c7.PNG)
![screen shot 05-16-17 at 12 26 pm](https://cloud.githubusercontent.com/assets/9212658/26141176/d3c18ffa-3ada-11e7-8884-39590ead6f97.PNG)
![screen shot 05-16-17 at 04 14 pm](https://cloud.githubusercontent.com/assets/9212658/26141189/e060511a-3ada-11e7-90be-e127648e6e76.PNG)

![screen shot 05-17-17 at 08 31 am](https://cloud.githubusercontent.com/assets/9212658/26141248/3531a1c6-3adb-11e7-9c84-402d5b1860b3.PNG)

Could someone plz be of any help about these errors ? Or already encounter errors like that ?

Thx in advance !
Best Regards !
Razgort

**Comment by pedrobaeza** [comment]
No, you haven't been redirected here. We have said that this is not a problem on the connector itself (both connector or connector_prestashop).
