### ISSUE TITLE
Problem exporting integer field with zero value

### ISSUE THREAD

**Issue by agb80** [OCA/connector#252]
For the Drupal connector we have being working for several time now we have the situation that we need to export the product.category sequence field to Drupal float field. 

By default odoo set sequence to zero (0) and that's ok. The problem is that when trying to export the field connector is replacing zero (0) value with False that translated to json is becoming an empty string. That empty string is causing Drupal to fail with database error: Incorrect integer value: '' for column 'weight'.

The cause for this change is condition `if not value` on line https://github.com/OCA/connector/blob/8.0/connector/unit/mapper.py#L146 as on python zero is equal to False.

PD: If any is interested you can find Drupal connector here: https://github.com/OpenPymeMx/connector-drupal

**Comment by flotho** [comment]
Hi @agb80 , does this one https://github.com/OCA/connector/pull/253 could also do the job ?

**Comment by agb80** [comment]
Hello @flotho that's my proposed fix to this issue.
