### ISSUE TITLE
Is Odoo 10.0<->Magento 1.x supported?

### ISSUE THREAD

**Issue by ghost** [OCA/connector#255]
https://www.odoo.com/apps/modules/10.0/connector/ mentons "v 10.0" and "Documentation: http://odoo-connector.com" but odoo-connector.com mentions only Odoo 9. So I'm wondering, is Odoo 10.0<->Magento 1.x supported ?

**Comment by ghost** [comment]
I see we have a very active community here :D I'd would even pay for such an open source Magento 1.x<->Odoo 10 connector.

**Comment by guewen** [comment]
Hi, you are not asking in the right place. This project is the connector framework which is unrelated to the magento implementation. Have a look at https://github.com/OCA/connector-magento/pull/255.
