### ISSUE TITLE
Socket is no socket in Jobrunner/runner.py/wait_notification

### ISSUE THREAD

**Issue by Zoltan-X** [OCA/connector#269]
Hello all,
Since a few days I'm getting on my Windows 10 development machine the follwing error when running the connector:

2017-11-19 11:37:25,914 5624 INFO ? openerp.addons.connector.jobrunner.runner: connector runner ready for db Babisto
2017-11-19 11:37:25,914 5624 INFO ? openerp.addons.connector.jobrunner.runner: database connections ready
2017-11-19 11:37:25,915 5624 ERROR ? openerp.addons.connector.jobrunner.runner: exception: sleeping 5s and retrying
Traceback (most recent call last):
  File "C:\opt\odoo\Babisto\XTRAaddons\connector\jobrunner\runner.py", line 351, in run
    self.wait_notification()
  File "C:\opt\odoo\Babisto\XTRAaddons\connector\jobrunner\runner.py", line 326, in wait_notification
    conns, _, _ = select.select(conns, [], [], SELECT_TIMEOUT)
error: (10038, 'Ein Vorgang bezog sich auf ein Objekt, das kein Socket ist')

I don't get it why,
but here are my circumstances:

Running Odoo 8 with connector 8.0.3.3 in Eclipse Oxygen on Windows 10 with Linuy Subsystem for Windows installed, but for eclipseprojects just not used,
with 5 workers, loading web,web_kanban,connector by config having ODOO_CONNECTOR_PORT & CHANNELS setup as enviroment. Since this week I'm getting the Error mentioned above,
but none the less jobs are processed somehow anyway.

I want to get rid of this exceptionmessage bloating my logs every 5 Seconds.

I'm accessing this error since this week and only on Win10

The Statement SocketError 10038 may in this case be something misleading, 
cause networking is fine in all cases,
it is more about a wrong value was passed as socket to sockethandler.

So far I've analysed this and the following lines are suspected as reasonable for te bug

        conns.append(self._stop_pipe[0])
        conns, _, _ = select.select(conns, [], [], SELECT_TIMEOUT)

In this case stop_pipe returns a tuple (3, 4) delivered from os.pipe and appends the first Value to conns and the select.select instantly fails, neither i could trace into this line to get more detail.

but the select.select expects in conns a list of connections and not an single integer value like it is as it happens.

refusing tp append the stop values by commenting 
        "conns.append(self._stop_pipe[0])"
out releases the error, but in this case I do not understand the puposes of handling with _stop_pipe!
os.pipe returns me allways a tuple with (3, 4) under windows, as under debian as well.

**Comment by guewen** [comment]
Windows is not supported.
