### ISSUE TITLE
Connector category should be "Connector"

### ISSUE THREAD

**Issue by ka-** [OCA/connector#27]
The category of the Connector should be "Connector" so the related modules and the Connector itself may be found with the same Category search. Without doing this, the main module does not seem to follow cinvension and all users would need to search at least two different categories to find the connector modules. 

Notice the documentation: openerp_connector/connector/doc/guides/bootstrap_connector.rst 
- The module category should be `Connector`.

**Comment by guewen** [comment]
Hi,

Thanks for your report.
The reason why it is not in the `Connector` category is that the `ir.module.category` is created in the XML files of the module so we can use link it with a group (https://github.com/OCA/connector/blob/6260f24adfc11ac855fcee1ed1d7b8dffc881d49/connector/security/connector_security.xml#L5). It was to avoid a situation where odoo creates the same `ir.module.category` at the module's installation but with a different xmlid.
From my observation, it was done like that in the official addons.

However, if you can prove that we can use the `Connector` category for the module and be sure to use the same xmlid in the security file, I have nothing against this change.

-- Guewen
