### ISSUE TITLE
Component: Into the Workcontext, the collection should not be an Odoo model

### ISSUE THREAD

**Issue by lmignon** [OCA/connector#275]
To initialize a WorkContext we must pass an Odoo model as collection parameter. 
https://github.com/OCA/connector/blob/11.0/component/core.py#L167
From the collection, only two attributes are required by the WorkContext:
* the model name is used as the collection name
* the environment. 

IMO this requirement on an Odoo model as collection parameter limits the possible uses of WorkContext. It is not possible to use it if you want to create a context for a collection name that is not an Odoo model.
In a specific use case, I would like to be able to initialize a WorkContext based on a collection name that comes from a pick list.
For this use case, I had to bypass this limitation by creating an object providing the two necessary attributes used by the WorkContext and pass as a collection parameter.

```python
class _PseudoCollection(object):
    def __init__(self, name, env):
        self._name = name
        self.env = env

class MyModel(models.Model):
   _name = 'my.model'
    collection = fields.Selection([('col1', 'col1'), ('col2', 'col2')])

    @contextmanager
    @api.multi
    def work_on(self, model_name, **kwargs):
        self.ensure_one()
        collection = _PseudoCollection(self.collection, self.env)
        yield WorkContext(
            model_name=model_name, collection=collection, **kwargs)


```
It would be nice to be able to do the same without the `_PseudoCollection`  class

**Comment by guewen** [comment]
You are right. I got the same issue with the Component Events implementation, that I circumvented with a customised subclass of WorkContext. I'm not very happy of this implementation but with no more experience at the time I preferred not to change the core WorkContext (and maybe didn't find an implementation that convinced me). I definitely agree that should be a good enhancement!
