### ISSUE TITLE
Component lookup my model with generic component

### ISSUE THREAD

**Issue by guewen** [OCA/connector#276]
Following the change in #272, should we apply a similar logic for models?

Example:

```python
class GenericExporter(Component):

    _name = 'generic.exporter'
    _inherit = ['base.exporter']
    _usage = 'record.exporter'

    def run(self, records):
        return self._export_items(records)


class SaleExporter(Component):

    _name = 'sale.exporter'
    _inherit = ['generic.exporter']
    _apply_on = 'sale.order'

    def run(self, records):
        return self.do_stuff(records)

```

For any model, the following snippet would return GenericExporter:

```python
exporter = work.component('record.exporter')
```

But for sale.order, it would return SaleExporter.

The current behavior is an error raised:
```
SeveralComponentError: Several components found for collection 'xx.backend', usage 'record.exporter', model_name 'sale.order'. Found: [<class 'odoo.addons.component.core.generic.exporter'>, <class 'odoo.addons.component.core.sale.exporter'>]
```

I tend to think that it should be rather safe regarding existing code (as it was an error) but I'm maybe overlooking the question.

@lmignon @simahawk any thoughts? :)

**Comment by simahawk** [comment]
:+1: this is what I'd love to have. In most of the cases we gonna benefit from this.

if you have a specific component fine. If not, fallback to the generic one.

It allows to not copy paste empty boiler plates again and again just to get a specific component that does exactly the same of the generic one.

Maybe, if you really want the possibility to raise an error if the specific one is missing you can probably have a kw `raise_if_not_found`. 

Yes, existing code is safe as long as _apply_on as precedence over generic.

**Comment by lmignon** [comment]
@guewen I fully agree with this proposal, which further increases modularity.
