### ISSUE TITLE
[IMP]Deal with translatable fields on export

### ISSUE THREAD

**Issue by flotho** [OCA/connector#282]
Hi,

I've recently struggled with values for translatable fields on this https://github.com/OCA/connector-odoo2odoo/pull/7
I've coded a fast implementation that make the job but is not generic at all composed of 2 parts :
* The mapper part : https://github.com/MindAndGo/connector-odoo2odoo/blob/10.0-migration/connector_odoo/components/mapper.py#L10
* And the mapper usage : https://github.com/MindAndGo/connector-odoo2odoo/blob/10.0-migration/connector_odoo/models/product/exporter.py#L89

This way of doing is not efficient and I would like to do it another way. We have good mappers for direct and method mapping here : https://github.com/OCA/connector/blob/10.0/connector/components/mapper.py#L765 . I propose to add a new list for translatable fields to simplify the multi lang management. As a pseudo code I propose something like this :
```
class ProductExportMapper(Component):
    _name = 'odoo.product.product.export.mapper'
    _inherit = 'odoo.export.mapper'
    _apply_on = ['odoo.product.product']
    direct = [  ('weight', 'weight'),
              ('standard_price', 'standard_price'),]
    translatable = [('name', 'name')]
```

And in the mapper class :

```
      def _map_translatable(self, record, from_attr, to_attr):
            #Implement firs a generic method on backend to get a default language code
            lang_code = self.backend_id.get_default_language_code()
            rec_lang = record.with_context(lang=lang_code)
            return rec_lang[field]

.../...
      for from_attr, to_attr in self.translatable:
            if callable(from_attr):
                attr_name = self._direct_source_field_name(from_attr)
            else:
                attr_name = from_attr

            if (not fields or attr_name in fields):
                value = self._map_translatable(map_record.source,
                                         from_attr,
                                         to_attr)
            result[to_attr] = value

```

@guewen , @lmignon  what is your point of view on this way of doing? maybe we could directly do this in _map_direct method but it looks to tricky from my point of view

Ih the orientation is correct I'll be able to propose a PR.

**Comment by simahawk** [comment]
@flotho I did something similar in a customer project, like this:

```python
class ExportMapper(AbstractComponent):
    _name = 'esb.export.mapper'
    _inherit = ['base.export.mapper', 'esb.base']
    _usage = 'export.mapper'

    translatable_keys = {
        # 'fr_FR': {
        #     'odoo_field': 'ext_field',
        # }
    }

    def translatable_langs(self):
        return self.env['res.lang'].search([
            ('translatable', '=', True)]).mapped('code')

    def finalize(self, record, values):
        values = super(ExportMapper, self).finalize(record, values)
        self.handle_translations(record, values)
        return values

    def handle_translations(self, record, values):
        """Collect and translate fields to be translated."""
        for lang in self.translatable_langs():
            if lang not in self.translatable_keys:
                continue
            translatable = self.translatable_keys[lang]
            data = record.source.with_context(
                lang=lang).read(translatable.keys())[0]
            for fname, extname in translatable.iteritems():
                values[extname] = data[fname]
```
Use case is a bit different I guess, but I'd prefer to not repeat direct mappings in another dict and just declare what I need to translate.
My $0.02 :wink:

**Comment by guewen** [comment]
I think there are slighty different uses cases, as proven by the 2 examples there, so I'm not sure we can have a generic implementation. I guess we could find an agreement on the API (a new `translatable` key with or without a language specified). But what should be the output? Sometimes translations are expected as sub-records, sometimes it's an entirely different dictionary (so we have to call the mapper once for the main language, once for the translation, ...).

So... maybe something we can do but need some thoughts :)

**Comment by flotho** [comment]
Well, I think that in some case it would be necessary.
Another example is this one : https://github.com/akretion/connector-prestashop/blob/10.0-mig-connector-prestashop-ak/connector_prestashop/components/importer.py#L499 
After import the code is firing all the map_values and we repass all the methods even those that don't need to be stored in different languages. In this particular case, perfs are immediately impacted by this.
Any additionnal thoughts to share?
