### ISSUE TITLE
How to Get environment and connector unit object 

### ISSUE THREAD

**Issue by ghost** [OCA/connector#293]
Earlier in odoo 10 connector i am importing using environment and connector.

But now i am trying with odoo11 .

@api.multi
    @odoo.addons.queue_job.job.job(default_channel='root.zoho')
    def import_batch(self, model_name, backend_id, filters=None):
        env = get_environment(None, model_name, backend_id)
        importer = env.get_connector_unit(Importer)
        importer.run(filters=filters)

But it giving error where to import get_environment and get_connector_unit ?

**Comment by guewen** [comment]
http://odoo-connector.com/guides/migration_guide.html

**Comment by ghost** [comment]
thanks for link.

But i am still unable to import record. 

Is there any detail docs ?
