### ISSUE TITLE
Duplicated event of component_event

### ISSUE THREAD

**Issue by nguyenducthuanuet** [OCA/connector#297]
Hi everyone,
Today I installed connector to subscribe an event when create new record of model 'res.partner' and listening it. But I got duplicated event occured 2 times. Is it an error of connector 11 ?
My Odoo version: 11
My event and my listener:
![screenshot from 2018-07-16 18-04-05](https://user-images.githubusercontent.com/20267242/42755541-c5f9c0d0-8922-11e8-9e4e-70a2058aebd0.png)
![screenshot from 2018-07-16 18-04-20](https://user-images.githubusercontent.com/20267242/42755545-cadce1ea-8922-11e8-84c8-1c8b093b87d5.png)
When event occured, What I got:
![screenshot from 2018-07-16 18-04-39](https://user-images.githubusercontent.com/20267242/42755554-d68e5d66-8922-11e8-8bd5-b4aa6644e8d9.png)
Thank everyone!

**Comment by guewen** [comment]
The `on_record_create` event trigger already exists, you don't need to add it in the base model again.

**Comment by nguyenducthuanuet** [comment]
Thank for your reply, I will close this issue.
