### ISSUE TITLE
Stuck workers in multi-processing mode

### ISSUE THREAD

**Issue by nilshamerlinck** [OCA/connector#302]
Hi, I would like to report here a weird case we faced in production where Odoo seemed to get stuck when starting with many (2000+) pending/failed jobs in the db.

We found a workaround but I'd rather hear your opinions before transforming it into a PR.

## Symptoms

- job runner starts properly and try to get some jobs to be processed, but all/most of them are immediately set back to pending state;
- workers exist:
```
$ ps aux | grep openerp-server | grep -v grep | wc -l
53
```
- they seem to be listening to the socket:
```
$ lsof -ni | grep ":9069 (LISTEN)" | wc -l
54
```
- but they don't answer to requests:
```
$ curl http://localhost:9069
(nothing)
```

Looking closer with `strace`, it seems that they are waiting for a lock to be released:
```
# strace -p66
Process 66 attached
futex(0x20cef70, FUTEX_WAIT_PRIVATE, 0, NULL
```

## Explanation

After a bit of googling, we found out [a well known python issue](https://bugs.python.org/issue6721) that seemed to match our case.

It helped us to understand what was happening:

### job runner is created as a thread of the main Odoo process:

```
INFO ? openerp.addons.connector.jobrunner: starting jobrunner thread (in prefork server)
```

### All NOT_DONE jobs are notified to the ChannelManager:

```
INFO ? openerp.addons.connector.jobrunner.runner: starting
INFO ? openerp.addons.connector.jobrunner.runner: initializing database connections
(...)
DEBUG ? openerp.addons.connector.jobrunner.channels: job d0937ead-d423-4d7c-b94c-a3952f0a96a0 marked pending in channel root.channel4(C:4,Q:1,R:0,F:0)
DEBUG ? openerp.addons.connector.jobrunner.channels: job d056584d-c167-4167-874a-e8738f189882 marked pending in channel root.channel4(C:4,Q:2,R:0,F:0)
(...)
```

[See initialize_databases()](https://github.com/OCA/connector/blob/383959afc6f1f71a45320d9cab45b84a05572ac7/connector/jobrunner/runner.py#L356)

### in the same time, http workers are spawned:

```
DEBUG db openerp.service.server: Multiprocess starting
```

[See here](https://github.com/odoo/odoo/blob/9.0/openerp/service/server.py#L608).

#### when it works, workers announce themselves:

```
INFO db openerp.service.server: Worker WorkerHTTP (24903) alive
INFO db openerp.service.server: Worker WorkerHTTP (24904) alive
INFO db openerp.service.server: Worker WorkerHTTP (24905) alive
(...)
```

#### in our weird case though, none of them or only 1 or 2 (note the gap in pids):

```
INFO db openerp.service.server: Worker WorkerHTTP (15612) alive
INFO db openerp.service.server: Worker WorkerHTTP (15618) alive
```

### why?

- The http workers are spawned while the job runner is busy initializing itself.
- The more pending/failed jobs we have, the more lines are printed by the job runner in the logfile.
- When printing a line in the logfile, the logging handler actually locks this logfile temporarily to avoid any other thread writing in it at the same time.
- Spawning a new http worker concretly means using `os.fork()` which basically copies the main Odoo process memory *including these locks*
- So, if a line is printed in the logfile just before `os.fork()` is called, the child process (http worker) will inherit a lock on the logfile that can't be released!
- Then, when this http worker will try to `_logger.info("Worker %s (%s) alive", ...)`, it will get stuck, infinitely waiting for the lock on the logfile to be released.

### 1) configuration: use syslog

To avoid these locks, we can configure this instance to use the [SysLogHandler](https://github.com/odoo/odoo/blob/9.0/openerp/netsvc.py#L134) by running Odoo with the `--syslog` switch (or its corresponding config parameter `syslog = True`).

### 2) code: give more time to the server to start all workers before starting the job runner

The job runner starts working after a [hard coded delay of 5 seconds](https://github.com/OCA/connector/blob/383959afc6f1f71a45320d9cab45b84a05572ac7/connector/jobrunner/__init__.py#L73).

We set [`START_DELAY = 60`](https://github.com/OCA/connector/blob/383959afc6f1f71a45320d9cab45b84a05572ac7/connector/jobrunner/__init__.py#L38) to avoid the issue.

## Conclusion

While these workarounds works, they are not satisfying.

We should dynamically wait until all workers are up before starting the job runner instead of relying on a static "safe" value (not so easy to implement without modifying Odoo's core; maybe using signals).

Or we should get the job runner its own process, which seems the best option as [it also kills other bugs with the same stone](https://github.com/OCA/connector/pull/288).

**Comment by guewen** [comment]
Impressive analysis. Running the job runner in its own process seems definitely the way to go.
