### ISSUE TITLE
component not compatible with cachetools >= 3.0.0

### ISSUE THREAD

**Issue by lmignon** [OCA/connector#311]
see changelog https://github.com/tkem/cachetools/blob/master/CHANGES.rst#v300-2018-11-04
I just noticed the error during tests in travis....
https://travis-ci.org/akretion/odoo-shopinvader/jobs/450747486#L9982
The error seems to come from the decorator `@cachedmethod(operator.attrgetter('_cache'),
key=lambda self, name: keys.hashkey(`   https://github.com/OCA/connector/blob/10.0/component_event/components/event.py#L228 since `self` is removed from `@cachedmethod` key arguments (breaking change).

What's the best fix? 
* Pin the version with  < 3.0.0 
* fix the code to work with 3.0.0 and pin the version of cachetools to >= 3.0.0?

**Comment by pedrobaeza** [comment]
I think the quick fix is the first option, but the ideal would be a third one, which is fix for 3.0.0, but being compatible also for < 3.0.0.

**Comment by lmignon** [comment]
I asked the author for more details on this change. In the meantime, I'm going to freeze the version. I don't want to try to write code that works differently depending on the version of the library used.
https://github.com/tkem/cachetools/issues/107#issuecomment-435819059

**Comment by pedrobaeza** [comment]
Yeah, let's see what is the answer of the author, and meanwhile it's the sanest fix.
