### ISSUE TITLE
[11.0] Are there any way to probe jobrunner's state in my code?

### ISSUE THREAD

**Issue by ZOOUQinn** [OCA/connector#318]
Sometime I have to restart odoo in 'job runner disable' mode, which means odoo is running without configuration lines like below:

```
[options]
workers = 6
server_wide_modules = web,queue_job

[queue_job]
channels = root:2
```

The job will keep in 'Pending' state endless if the job runner is starting incorrectly.

So, Are there any way to probe jobrunner's state, then code can call the execution of a job method in an SYNCHRONOUS (without delay) process?

**Comment by guewen** [comment]
AFAIK there is no way

**Comment by guewen** [comment]
Closing in favor of https://github.com/OCA/queue/issues/113
