### ISSUE TITLE
[12.0] message_subscribe_users is removed from 12.0

### ISSUE THREAD

**Issue by omalbastin** [OCA/connector#320]
https://github.com/OCA/connector/blob/8d2a32447eb9d3504759af9aafa502bdc30f7f1f/connector/models/checkpoint.py#L113

Reference:
https://github.com/odoo/odoo/commit/b6d2351df45bdd049e42e828743b5dd2f1941649

**Comment by guewen** [comment]
Thanks for the notice, fixed in https://github.com/OCA/connector/pull/315
