### ISSUE TITLE
[v10] Not A Issue: Is it possible to extend the functionality without modifying the core modules

### ISSUE THREAD

**Issue by omalbastin** [OCA/connector#345]
I have reported the same issue under connector_prestashop repo.

Im trying to sync between product pricelist items and specific prices to prestashop. So I create a new module and components(adapter, binder, importer, exporter,listener) for specific prices are added. then 
`class SpecificPriceProductTemplateImporter(Component):
    _inherit = 'prestashop.product.template.importer'
 `
and added codes to sync the pricelist items.

but now the error getting is 
`NoComponentError: No component found for collection 'prestashop.backend', usage 'prestashop.importer', model_name 'prestashop.product.template'.
`

In connector_prestashop module I saw https://github.com/OCA/connector-prestashop/blob/af05419e40bfc9fe6a738fb6b60bde2b4cb7c1e7/connector_prestashop/models/product_template/importer.py#L682

So do I have to update the core modules. ?

Edit: I was checking the core.py under components module and found that in the lookup method(line107) generator functions are not working. when i change the generator functions to listcomprehensions, i was able to get it.

**Comment by guewen** [comment]
Hi,

You can inherit a component the same way you would with an odoo model, by using `_inherit`. Can you show your code to see what could be the issue?

You should never need to change the core modules.
