### ISSUE TITLE
[8.0] Question: How to really kill the running job process?

### ISSUE THREAD

**Issue by kittiu** [OCA/connector#360]
We have been using this module for its good. Now, I have some problem trying to really stop some running process in production.

I read and understand from the Caveat here http://odoo-connector.com/8.0/guides/jobrunner.html that I can use SQL to set the state. But this will not work for the job already started. (restart server is not possible).

Are there anyway that we can really "kill" the running job, either by command line or others?

Thanks!

**Comment by guewen** [comment]
If you cannot restart the process that is executing the jobs, you likely can't stop a running job (or you have to `kill` the correct pid which seems tricky). If you can't stop/restart the service that runs the jobs the workers that execute the jobs are the same as workers processing HTTP requests for the users, you could consider starting a separated service for jobrunner + job workers.

**Comment by kittiu** [comment]
Thank you for the answer. So, it seem to have 2 options, am I right?

1. find the way to find pid although it is tricky.
2. find way to start the job with separated service for job runner. and find way to restart only it.

Frankly, I do think I can do any of both myself. Given this is used in production for NSTDA (our OCA sponsor), I think they are ok to pay for the consulting service.

If you don't mind, can I email to you after this?
