### ISSUE TITLE
Rules for checkpoints

### ISSUE THREAD

**Issue by OSguard** [OCA/connector#37]
We use the connector with the magento-connector framework together. We have various problems because having different products with the same default_code after import.
So we want to have a check on Import or after import if the current default_code not exist. For sale.orders we can defined "sale.exception". We have not similar yet as "checkpoint.exception" that we execute the import.job (instead trigger a exception their), to check in general after we have execute a import job, if everything is fine or what is done.

So our workaround is, to patch the button on reviewed to include the check their.

``` python
class connector_checkpoint(Model):
    _inherit = 'connector.checkpoint'

    def reviewed(self, cr, uid, ids, context=None):
        for checkpoint in self.browse(cr, uid, ids, context=context):
            if checkpoint.model_id.model == 'product.product':
                product_pool = self.pool.get('product.product')
                product = product_pool.browse(cr, uid, checkpoint.record_id, context=context)
                product_ids_with_this_sku = product_pool.search(cr,
                                                                uid,
                                                                [('default_code', '=', product.default_code)],
                                                                context=context)
                if len(product_ids_with_this_sku) > 1:
                    raise except_orm(_('Error'),
                                     _('there more then one product with the reference %s')
                                     % product.default_code)
        return super(connector_checkpoint, self).reviewed(cr, uid, ids, context=context)
```

May it would be better to extend the checkpoint concept to defined rules, to display to the user?

**Comment by guewen** [comment]
That's a good idea. How do you imagine to implement the rules?
The `sale.exception` is straightforward because it blocks the sales orders in draft. It seems less easy with the products, they are already created once the job finish.
What you have done with the checkpoint seems already nice though.

**Comment by lmignon** [comment]
I agree with @guewen, that's a good idea. I'm looking forward to see how it will be implemented.

**Comment by OSguard** [comment]
I have not make details on implementation. Just want to share the idea. Maybe someone has already a concept ready. So as it seems not i / we will make a assumption.

**Comment by OSguard** [comment]
@guewen @sebastienbeau and me discuss the following concept of merging:
- connector.checkpoint
- sale.exception
- purchase.exception

the concept would be the following

rule(Model)
- name
- description
- sequence
- model_id (relation to ir_model)
- active
- (code) should be removed and move to a function
- type (exception, notice)

checkpoint (Model)
- rule_id
- record_id
- state (new, resolved, ignored)

We want to have a list view where you see all checkpoints and can filter of new one how need to resolve.
Also want to display all checkpoints in a tree view of the related model.
With the state option you can force to override one check for a specific model.
The type=notice mean that automation don't stop on that.

If we remove the code field (because writing code in xml is not good and the customer should not should change it), we need a new concept how to register a new check as a function of a model?

wish: support placeholder for description.

**Comment by lmignon** [comment]
LGTM :+1:

**Comment by flotho** [comment]
Hi,
What's the progress on this issue, do we already have some improvements ?
regards
