### ISSUE TITLE
TravisCI redundant tests?

### ISSUE THREAD

**Issue by dreispt** [OCA/connector#4]
Looking at the `.travis.yml` I notice that [odoo tests run twice](https://github.com/OCA/connector/blob/master/.travis.yml#L40-L41).
Looking at the [Travis build log](https://travis-ci.org/OCA/connector/builds/28505149) I confirm that idea.

Could the [first test call](https://github.com/OCA/connector/blob/master/.travis.yml#L40) be redundant?

**Comment by bwrsandman** [comment]
[Explained in the comments](https://github.com/OCA/connector/blob/master/.travis.yml#L35), the first run is to initialise the addons, the tests aren't run. The second run is the one with `--test-enable`

Without this double run, travis will test all dependency addons, which are redundant.

**Comment by dreispt** [comment]
Of course. Thanks for pointing it out.
