### ISSUE TITLE
Use of 'should_import' leads to failed sync

### ISSUE THREAD

**Issue by thomaspaulb** [OCA/connector#409]
In my custom exporter I'm using [_should_import](https://github.com/OCA/connector/blob/13.0/connector/components/synchronizer.py#L125) in order to skip records based on some condition.

However, this makes `self.external_id` remain `False`, which then leads to an exception on [bind](https://github.com/OCA/connector/blob/13.0/connector/components/synchronizer.py#L159), [here](https://github.com/OCA/connector/blob/13.0/connector/components/binder.py#L101).

Thus, any job corresponding to a record that I've tried to skip, fails, and I get an email about a failed job.

What I would want is the job not failing, but instead not occurring at all; or getting cancelled - this will allow me to respond to 'real' sync failures only, and not the ones I actually wanted to skip.

Is this a known issue, or should I be using another mechanism to skip records from sync?

**Comment by guewen** [comment]
I suppose you could override the run method and do your check before calling super?

Reading the code, l agree the role of _should_import is not obvious. It's role is to tell if the exporter should schedule an import of the record, the use case being that the last update (sync date) is earlier than the last update date on the external system and we want to import updated data from it after the export to get the updated values.

An example in _should_import would be to read the update date on the external system's API and compare it with the sync date of the binding.

**Comment by thomaspaulb** [comment]
Thanks for explaining!
