### ISSUE TITLE
[Draft] Job channels

### ISSUE THREAD

**Issue by guewen** [OCA/connector#43]
# Job channels
## Introduction

This is a document explaining how would be implemented the channels in the jobs queue.  It is in draft and will be modified.  At time of writing, the _what_ and _how_ regarding the implementation has not been decided yet so read it with caution.
## What they resolve

In the jobs queue, jobs are all pushed in a queue.  Then, one or many processes take them from the queue and run them one after the other.

This has serious limitations in real use cases:
- If one system does not support to be hit by several workers at the same time (Magento, look at me), we will be limited to use one worker even if we have several connectors
- If tasks are very long to execute, they could clog the queue and prevent other little jobs to be executed

This is were the channels come in handy.
- Let's say this very heavy, long job clutters the workers, put it in a channel 'slow' and place only 1 worker on it, keep the other workers execute the rest
- Or we have this system that want to be touched gently, start only 1 worker that will handle all the channels of this system, and 3 other workers for the other connectors
### Assignation of a channel to a job

All jobs that have no channel specified goes into a `default` channel.

A channel can be specified on using the keyword argument `channel` of the `job` decorator:

``` python
@job(channel='channel`)
def import_record(session, model_name, backend_id, external_id):
    pass
```

Sub-channels allow more fine-grain control on the execution of the jobs by the workers.

``` python
@job(channel='channel.subchannel.subsubchannel`)
def import_record(session, model_name, backend_id, external_id):
    pass
```
### Workers

If nothing is specified when the workers are started, the workers watch all the channels.

The usual command starts 2 workers that will executes all the jobs whatever their channel is. So it works in a backward compatible manner:

``` bash
$ PYTHONPATH=/path/to/server connector/openerp-connector-worker --config
configfile --workers=2
```

The same thing could be done with:

``` bash
$ PYTHONPATH=/path/to/server connector/openerp-connector-worker --config
configfile --workers=all:2
```

`all` is a reserved channel which shouldn't be used in the `job` decorator.

More control is possible using the `--workers` option.

1 worker on `default`, 1 on `system_a`, 2 on `system_b`.

```
--workers=default:1,system_a:1,system_b:2
```

1 worker on `default`, 1 on `system_a.import`, 1 on `system_a.export`, 2 on `system_b`.

```
--workers=default:1,system_a.import:1,system_a.export:1;system_b:2
```

Several channels can be watched by a worker:

So we want 2 workers sharing all the imports of system A and B, and 1 for the export of both systems:

```
--workers=system_a.import:system_b.import:2,system_a.export:system_b.export:1
```

At last, we can exclude a subchannel with `~`, for instance if it is an heavy task that we want to exclude:
So we want 2 workers for system A but another worker for one specific job of this system:

```
--workers=system_a:~system_a.export.heavyjob:2,system_a.export.heavyjob:1
```

**Comment by lmignon** [comment]
@guewen  Thank you for sharing your ideas.
Job Channels seems to  be a good idea to improve the connector scalability. I'm not sure it's the right/only solution for long running jobs. With your proposal, if you have 2 long jobs to process, both will be put in the same channel even if others workers are available and we loses the benefit of parallelization. One limitation in the current implementation is the way jobs are assigned to workers. In a lot of cases, we've one worker with a lot of jobs assigned for processing and others workers unused. If we want to fully take advantage of multi processing, I think we should also improve the assignment process to assign jobs to a worker only when it is free. Channels and an improved assignment process, should further improve the connector framework...

(2¢) , regards,

lmi

**Comment by pedrobaeza** [comment]
It seems good, but it relies in server initialization parameters, so you must know what are the channels (very error prone), and depends on your deployment strategy.

Can't it be configured in any way via backend?

**Comment by guewen** [comment]
@pedrobaeza The workers are launched at the very beginning when you start the process, even before initializing the connection to the DB, so no you can't configure it on the backend.

**Comment by pedrobaeza** [comment]
I mean the channels to bind each worker, not the workers themselves.

**Comment by guewen** [comment]
@lmignon In your example with the long running jobs, couldn't you start 2 workers for your long jobs if you know you have many of them and want to parallelize them? (perhaps the jobs queue is _not_ the solution for very long running jobs)

Could the assignment on one worker be related to the fact that jobs are pushed by packs of 50 in the queues?

Another place where I would love to see improvement is the usage of the pg listeners to avoid the workers to poll the database looking for the jobs. I started an experimental branch a whiiile ago but did not worked on it anymore since: https://code.launchpad.net/~openerp-connector-core-editors/openerp-connector/7.0-connector-pg-notify-listen-experimental

@pedrobaeza In my draft, the channels bound to the jobs are fixed. Being capable to configure them is a interesting idea, but would it really be less error-prone?
Just thinking out loud:
- Job definitions are just functions today, totally unrelated to the database or the backend
- We could have a new model that allows to configure the channel of the jobs
- We would need to have a routine at some points that looks for all the functions decorated by `job` and create a record in this model if it not yet exists (any ideas how? the decorator is of course applied when the python file is executed so not at this moment)
- Each time a job is delayed, we would have to read the channel in this model, a cache must be used

It looks possible and attractive! Also, it would obviate the necessity of subchannels, which will make the workers happy when they have to search for jobs. My most important doubt is about the third point.

**Comment by sebastienbeau** [comment]
Hi @guewen really really great idea ! It's will solve a lot of issue regarding the export of data into magento (magento hate multi worker :weary: ) and will give a better way to manage priority (importing order and exporting stock have an high priority).
Thanks for sharing this idea !

**Comment by lmignon** [comment]
@guewen 

> Could the assignment on one worker be related to the fact that jobs are pushed by packs of 50 in the queues?

Yes it is. So even if you have n workers started,  the probability to have all your jobs assigned to the same workers is high. 

> Another thing I would love to see improvement is the usage of the pg listeners to avoid the workers to poll the database looking for the jobs ...

Seems to be a way to improve the assignment process and have a better balancing for the jobs processing between workers. I saw your branch , but even if we are impacted by this problem, I never had time to look more deeper.

**Comment by guewen** [comment]
Job channels have been implemented, mainly by @sbidoul in https://github.com/OCA/connector/releases/tag/3.1.0 so I close this issue.
