### ISSUE TITLE
Events: how to notify when the event really happened ?

### ISSUE THREAD

**Issue by nomed** [OCA/connector#439]
**Is your feature request related to a problem?**
the event is generated before the record has been stored in db.
That means we will propagate an event that hasn't really happened in case something fails on some inherited model.

**Describe the solution you'd like**
Ideally there should be the possibility to have an "on_record_created" and not only "on_record_create"

**Additional context**
There may be cases where it is useful to propagate something that's going to really happen, but what if we want to 
be sure we're propagating something that really happened ?
If there is already a solution to this, please drive me there :)

**Comment by simahawk** [comment]
The event is already triggered AFTER the records are created https://github.com/OCA/connector/blob/16.0/component_event/models/base.py#L105
If you want to do something after the transaction has been committed you should use a post commit hook. 
Example https://github.com/OCA/connector-interfaces/blob/14.0/connector_importer_source_sftp/components/event_listeners.py#L79
