### ISSUE TITLE
Use Postgres advisory locks

### ISSUE THREAD

**Issue by guewen** [OCA/connector#45]
Improvement: replace the `FOR UPDATE` locks in the worker by [Advisory Locks](http://www.postgresql.org/docs/current/static/explicit-locking.html#ADVISORY-LOCKS)

Here is the part that could be improved with that: https://github.com/OCA/connector/blob/8.0/connector/queue/model.py#L309-L356

It is more efficient, particularly, locks are held in memory so a lock does not incur a write on the disk.

Beware: advisory locks are application-level locks, so they won't prevent users to write on the job using the ORM, see if that should be prevented in the crud methods.

See also http://hashrocket.com/blog/posts/advisory-locks-in-postgres, http://stackoverflow.com/a/25514889

**Comment by lmignon** [comment]
@guewen it sounds interesting. Do you also expect a better balancing of the job's assignment to the queues?

**Comment by guewen** [comment]
@lmignon I don't think it could improve the balancing. 

Just an idea popping out of my head: we could add some variance here https://github.com/OCA/connector/blob/8.0/connector/openerp-connector-worker#L100 so that the workers process work not every time in the same order. Ideally we should make them roll, something like:
- loop 1
  - worker 1: sleep 15
  - worker 2: sleep 15 + 1
  - worker 3: sleep 15 + 2
  - worker 4: sleep 15 + 3
- loop 2
  - worker 1: sleep 15 + 1
  - worker 2: sleep 15 + 2
  - worker 3: sleep 15 + 3
  - worker 4: sleep 15
- loop 3
  - worker 1: sleep 15 + 2
  - worker 2: sleep 15 + 3
  - worker 3: sleep 15
  - worker 4: sleep 15 + 1
    and so on

**Comment by guewen** [comment]
No longer required with the new job runner.
