### ISSUE TITLE
Unable to install on Odoo 14 CE Ubuntu 20

### ISSUE THREAD

**Issue by austinnakuru** [OCA/connector#452]
Hi, 
I am unable to install the module connector on odoo 14 CE running on Ubuntu 20.  I keep getting the error

" Unable to install module "component" because an external dependency is not met: Python library not installed: cachetools '

Tried installing cachetools using the following methods but doesn't work

pip3 install cachetools==2.0.1
pip3 install cachetools

In both cases i reboot the server but still get the error;

" Unable to install module "component" because an external dependency is not met: Python library not installed: cachetools '

Regards

**Comment by simahawk** [comment]
I have py3.9 on Ubuntu 22.04 and works fine w/ `cachetools==5.2.0`.
I have also py.37 on Debian buster which works fine w/ `cachetools==4.2.2`.

Are you sure you are using the same python for odoo and for installing the lib?
I'd recommend trying from scratch in a virtualenv.
