### ISSUE TITLE
New Job Runner does not recover interrupted jobs

### ISSUE THREAD

**Issue by guewen** [OCA/connector#68]
Step to reproduce:
- Start the Job Runner with a capacity of root:4
- Create dozens of jobs (e.g. with base_import_async)
- Shutdown the server during the execution of the jobs, 4 of them should be in `started` state
- Start again the server with job runner of capacity of root:4
- The root channel shows that 4 jobs are running, but in fact none of them are running: these are the old jobs that have been interrupted

Expected:
The jobs are reset to `pending`.

**Comment by guewen** [comment]
@sbidoul an idea?

**Comment by sbidoul** [comment]
I would expect a normal shutdown of Odoo to finish ongoing transactions (I kind of remember having seeing code doing that in Odoo server). So jobs left in started state would mean there has been a hard crash of the server.

I remember we've had the same experience with workers: after a hard crash, jobs were left in started state and had to be requeued manually. 

At some point I was thinking of storing the PID/TID of the process that is running the job so we could dectect dead jobs to warn the user and/or requeue them automatically.

**Comment by guewen** [comment]
> I remember we've had the same experience with workers: after a hard crash, jobs were left in started state and had to be requeued manually.

It should not happen in the normal workers:
- jobs are attached to a `worker`
- a `worker` has to send an `alive` signal every `n` seconds otherwise they are deleted from the database → the jobs are detached from their `worker`
- jobs which are not `pending` and are not attached to any `worker` are reset to `pending`

> I would expect a normal shutdown of Odoo to finish ongoing transactions (I kind of remember having seeing code doing that in Odoo server). So jobs left in started state would mean there has been a hard crash of the server.

Now that you say that, it seems logical to me. It should at least.
In my case, it happens everytime I shutdown my server, but my server runs with `supervisord`, I suspect it to send a more brutal signal (SIGKILL I guess) if a SIGTERM does nothing (I have to check).

> At some point I was thinking of storing the PID/TID of the process that is running the job so we could dectect dead jobs to warn the user and/or requeue them automatically.

Could be nice.

**Comment by sbidoul** [comment]
@guewen , I believe there is bug in Odoo graceful shutdown: https://github.com/odoo/odoo/pull/6738

**Comment by guewen** [comment]
odoo/odoo#6738 has been merged, so along with #69 this issue is resolved in 8.0 :smile:
