### ISSUE TITLE
is_module_installed() alternative

### ISSUE THREAD

**Issue by bealdav** [OCA/connector#85]
Hi, @guewen 

Since the deprecated install_in_connector(), I've tried to search a replacement like here.

https://github.com/akretion/base-import-mapping/pull/1/files#diff-823631ecb7bd71a0feea07153d79aa38R196

I haven't saw your new method is_module_installed, oups, but 

``` python
if module_name in list(self.env.registry._init_modules):
```

works like a charm.

It seems to be a low level attribute defined here
https://github.com/odoo/odoo/blob/8.0/openerp/modules/registry.py#L56

Don't you think it could be used safely as an alternative of is_module_installed() at least for future Connector version ?

cc @ccomb @StefanRijnhart @sebastienbeau @rvalyi

**Comment by guewen** [comment]
From what I read yes it seems it can be used. We would rely on an internal so the downside is that it can change in the stable version, but I think the chances of it to be changed are low.
The change is easy, needs to replace this call https://github.com/OCA/connector/blob/8.0/connector/session.py#L265 by the check and to deprecate the method in `ir.module.module`.
